### ISSUE TITLE
use junit for summary generation

### ISSUE THREAD

**Issue by dcbaker** [dcbaker/piglit#4]
being able to import junit for summary generation would be useful.

It might be worth trying to encode additional information in the junit somewhere, maybe there's a comment tag or something that we can use?

**Comment by janesma** [comment]
This feature gates the usage of Intel's CI by external contributors.  Both Emil and Paul have recently pushed broken patches that would have been detected by our CI.  Tim Arceri is eager to use our system as well.

**Comment by dcbaker** [comment]
I'm working this actively at the moment.

**Comment by dcbaker** [comment]
This is basically done, the only outstanding problem is comparing json to junit

**Comment by janesma** [comment]
I'm satisfied.  You can call it done if you are happy with it.
