### ISSUE TITLE
Report concurrently running tests with failure output

### ISSUE THREAD

**Issue by janesma** [dcbaker/piglit#6]
Concurrent execution is both a critical feature of piglit, however bugs which manifest with concurrent are difficult to debug.

Currently, BSW generates random failures with concurrent execution, but we have no way to narrow down which test triggers the failures (because it passes).

Also GPU hangs generate failing tests, but no information exists to help us determine which test triggered the hang.  For this reason, narrowing down gpu hangs is a time-consuming process.

When a test fails, additional output should be appended to the failure tags, listing all tests whose execution overlapped the failure.  This information should be obtainable from piglit's process management infrastructure, or from the files which currently track incomplete test runs.

**Comment by janesma** [comment]
Easiest way to do this would be to include the start and end times with each test.  Postprocessing could easily figure out the concurrency.

**Comment by dcbaker** [comment]
We already store times, but as total runtimes rather than start and end separately. We could easily replace  that time with a separate start and end time stamp

**Comment by dcbaker** [comment]
fixed by: wip/timestamps

**Comment by dcbaker** [comment]
fixed by 68ca773
